Added Operator Section to GREL Functions Page
OpenRefine/openrefine.org pull request #295
Opened 2024-02-08 08:57 UTC by aayushk9

Fixes #289 
 Introduced an 'Operator' section to the GREL functions page, improving user accessibility to information about operators in GREL.

2024-02-08 19:23 UTC, aayushk9 commented
@wetneb Can you review you this PR?

2024-02-08 19:24 UTC, aayushk9 commented
@wetneb Can you review this PR?

2024-02-08 20:14 UTC, tfmorris requested changes
Thanks a lot for the contribution! Operators are distinct from Functions, so this would probably fit better on the GREL page than on the GREL Functions page.

I made a few other small comments inline.

2024-02-08 20:14 UTC, tfmorris commented on docs/manual/grelfunctions.md
> +`==` and `!=` operators can be used for string equality and inequality. For example, `"a" == "b"` returns false and `"a" != "b"` returns true.
These work for any data type, not just strings.

2024-02-08 20:14 UTC, tfmorris commented on docs/manual/grelfunctions.md
> +The `<` operator checks if the left operand is less than the right operand and `<=` checks if it's less than or equal to. Similarly `>` verifies if the left operand is greater than the right and `>=`
These operators work for number, strings, and dates.

2024-02-08 20:14 UTC, tfmorris commented on docs/manual/grelfunctions.md
> +- [Logical Operators](https://openrefine.org/docs/manual/grelfunctions#boolean-functions)
```suggestion
- [Logical Functions](https://openrefine.org/docs/manual/grelfunctions#boolean-functions)
```

2024-02-08 20:14 UTC, tfmorris commented on docs/manual/grelfunctions.md
> +
Move (or copy?) the division documentation from the Math Functions page to here.

2024-02-09 04:41 UTC, aayushk9 commented
Hello @tfmorris
Thank you for pointing that out. I'll make the required changes

2024-02-09 09:55 UTC, ostephens commented
LGTM thank you @aayushk9 for the contribution and @tfmorris for review

2024-02-10 11:16 UTC, closed without merging

2024-02-10 11:22 UTC, wetneb commented
@aayushk9 it looks like you deleted your fork before this pull request was formally accepted, which means that your changes have not yet made it into OpenRefine's website. Was that intended?
It could still be possible to salvage your work by recovering it from [this view](https://github.com/OpenRefine/openrefine.org/pull/295/files), but it's a little more involved!

2024-02-10 13:47 UTC, aayushk9 commented
@wetneb Apologies for the inconvenience. I mistakenly deleted the forked repository. To rectify this, I've made all the necessary changes and created a new pull request. You can find the new pull request [here](https://github.com/OpenRefine/openrefine.org/pull/296)