Update running.md adding proxy to JVM preferences
OpenRefine/openrefine.org pull request #398
Opened 2024-10-31 04:05 UTC by antoine2711

Update running.md to add the proxy to JVM preferences

2025-02-03 14:53 UTC, magdmartin commented
@antoine2711, this PR is currently in draft mode. Are you planning to continue working on it? I let someone from the Dev team review it.

2025-02-03 18:38 UTC, antoine2711 commented
> @antoine2711, this PR is currently in draft mode. Are you planning to continue working on it? I let someone from the Dev team review it.

Sure, @magdmartin, let's put it to review.

Regards, Antoine

2025-02-03 22:40 UTC, wetneb reviewed
I think the "Setting the" parts are a bit redundant - it's already clear because the table is a list of settings…

2025-02-04 01:29 UTC, thadguidry requested changes

2025-02-04 01:29 UTC, thadguidry commented on docs/manual/running.md
> +|Setting the proxy host or IP|`-Dhttp.proxyHost`|yourproxyhost or 192.168.1.10
```suggestion
|Proxy host or IP|`-Dhttp.proxyHost`|example.org or 192.168.1.10
```

2025-02-04 01:29 UTC, thadguidry commented on docs/manual/running.md
> +|Setting the proxy port|`-Dhttp.proxyPort`|8080
```suggestion
|Proxy port|`-Dhttp.proxyPort`|8080
```

2025-02-04 01:53 UTC, thadguidry commented
Looks good to me in Netlify preview:
![image](https://github.com/user-attachments/assets/699ae6ed-dcf1-4ea8-a71a-9d052f91552d)

2025-02-04 02:01 UTC, merged